---
blank_issues_enabled: true
contact_links:
    - name: ğŸ“œ Code of Conduct
      url: https://github.com/adchitects/.github/blob/main/CODE_OF_CONDUCT.md
      about: In any way you want to interact with us, you need to abide by the terms of our adopted Code of Conduct.

    - name: â“ Support
      url: https://github.com/adchitects/configs/discussions
      about: This issue tracker is not for support questions. Please use Discussions -> Q&A instead.
